import type { AstroContent } from "./types";

const ord = (n: number) => `${n}${n === 1 ? "st" : n === 2 ? "nd" : n === 3 ? "rd" : "th"}`;

export const en: AstroContent = {
  signs: ["Aries (Mesha)", "Taurus (Vrishabha)", "Gemini (Mithuna)", "Cancer (Karka)", "Leo (Simha)", "Virgo (Kanya)", "Libra (Tula)", "Scorpio (Vrischika)", "Sagittarius (Dhanu)", "Capricorn (Makara)", "Aquarius (Kumbha)", "Pisces (Meena)"],
  planets: { sun: "Sun (Surya)", moon: "Moon (Chandra)", mars: "Mars (Mangal)", mercury: "Mercury (Budh)", jupiter: "Jupiter (Guru)", venus: "Venus (Shukra)", saturn: "Saturn (Shani)", rahu: "Rahu", ketu: "Ketu" },
  nakshatras: ["Ashwini", "Bharani", "Krittika", "Rohini", "Mrigashira", "Ardra", "Punarvasu", "Pushya", "Ashlesha", "Magha", "Purva Phalguni", "Uttara Phalguni", "Hasta", "Chitra", "Swati", "Vishakha", "Anuradha", "Jyeshtha", "Mula", "Purva Ashadha", "Uttara Ashadha", "Shravana", "Dhanishta", "Shatabhisha", "Purva Bhadrapada", "Uttara Bhadrapada", "Revati"],
  tithis: ["Pratipada", "Dwitiya", "Tritiya", "Chaturthi", "Panchami", "Shashthi", "Saptami", "Ashtami", "Navami", "Dashami", "Ekadashi", "Dwadashi", "Trayodashi", "Chaturdashi", "Purnima"],
  purnima: "Purnima",
  amavasya: "Amavasya",
  paksha: { shukla: "Shukla Paksha", krishna: "Krishna Paksha" },
  varas: ["Sunday (Ravivar)", "Monday (Somvar)", "Tuesday (Mangalvar)", "Wednesday (Budhvar)", "Thursday (Guruvar)", "Friday (Shukravar)", "Saturday (Shanivar)"],
  yogaNames: ["Vishkambha", "Priti", "Ayushman", "Saubhagya", "Shobhana", "Atiganda", "Sukarma", "Dhriti", "Shula", "Ganda", "Vriddhi", "Dhruva", "Vyaghata", "Harshana", "Vajra", "Siddhi", "Vyatipata", "Variyana", "Parigha", "Shiva", "Siddha", "Sadhya", "Shubha", "Shukla", "Brahma", "Indra", "Vaidhriti"],
  karanas: ["Bava", "Balava", "Kaulava", "Taitila", "Gara", "Vanija", "Vishti", "Shakuni", "Chatushpada", "Naga", "Kimstughna"],
  houseOrdinal: (n) => `${ord(n)} house`,
  houseTopics: ["self, body and personality", "wealth, family and speech", "courage, siblings and communication", "home, mother and inner peace", "children, intellect and creativity", "health, service and competition", "marriage and partnerships", "longevity, research and transformation", "fortune, dharma and the guru", "career, status and karma", "gains, income and friendships", "spirituality, expenses and moksha"],
  lagnaTraits: [
    "Mesha lagna gives a pioneering, energetic and courageous nature. You like to lead, act quickly and thrive on challenges; patience is your key lesson.",
    "Vrishabha lagna makes you steady, reliable and fond of comfort and beauty. You build slowly and securely, with a strong eye for value and aesthetics.",
    "Mithuna lagna gives a curious, witty and communicative mind. You adapt quickly, love learning and connect people and ideas with ease.",
    "Karka lagna blesses you with deep sensitivity, care and intuition. Family and emotional security are central, and you nurture everyone around you.",
    "Simha lagna gives dignity, warmth and natural leadership. You shine in public roles and are generous, loyal and self-confident.",
    "Kanya lagna makes you analytical, precise and service-minded. You excel at details, health and problem-solving, though you may be self-critical.",
    "Tula lagna gives charm, balance and a strong sense of fairness. Relationships, art and diplomacy come naturally to you.",
    "Vrischika lagna gives intensity, depth and determination. You are perceptive, private and capable of great transformation and research.",
    "Dhanu lagna blesses you with optimism, wisdom and love of freedom. Dharma, travel, teaching and higher learning inspire you.",
    "Makara lagna makes you disciplined, practical and ambitious. You rise steadily through hard work, responsibility and patience.",
    "Kumbha lagna gives an original, humanitarian and independent mind. You think ahead of your time and value community and ideals.",
    "Meena lagna gives compassion, imagination and spiritual depth. You are intuitive, artistic and naturally drawn to the divine.",
  ],
  moonTraits: [
    "With the Moon in Mesha, your emotions are quick and passionate; you need action and independence to feel at ease.",
    "With the Moon exalted in Vrishabha, you enjoy emotional stability, contentment and a love of simple pleasures.",
    "With the Moon in Mithuna, your mind is restless and curious; conversation and variety keep you happy.",
    "With the Moon in its own sign Karka, you are deeply caring, intuitive and attached to home and family.",
    "With the Moon in Simha, you have a proud, generous heart and need appreciation and self-expression.",
    "With the Moon in Kanya, your mind is analytical and orderly; being useful brings you peace.",
    "With the Moon in Tula, you seek harmony and companionship and dislike conflict.",
    "With the Moon in Vrischika, emotions run deep and intense; learning to let go brings great strength.",
    "With the Moon in Dhanu, you are optimistic and philosophical, happiest when exploring and learning.",
    "With the Moon in Makara, you are emotionally reserved and responsible, finding security in achievement.",
    "With the Moon in Kumbha, you are emotionally independent, friendly and drawn to ideals and causes.",
    "With the Moon in Meena, you are sensitive, compassionate and dreamy, with strong spiritual intuition.",
  ],
  planetNature: {
    sun: "authority, confidence, vitality and recognition from those in power",
    moon: "emotional sensitivity, public connection and a caring disposition",
    mars: "energy, courage, drive and a competitive spirit",
    mercury: "intelligence, communication skills, business sense and wit",
    jupiter: "wisdom, blessings, growth, good counsel and prosperity",
    venus: "comfort, beauty, love, art and material pleasures",
    saturn: "discipline, delays that mature into lasting results, and hard-earned success",
    rahu: "strong ambition, unconventional paths and sudden rises, with some restlessness",
    ketu: "detachment, spiritual insight and past-life skills, with some uncertainty",
  },
  dignity: {
    exalted: "where it is exalted and gives excellent results",
    debilitated: "where it is debilitated and needs strengthening",
    own: "in its own sign, giving strong and stable results",
    friendly: "in a friendly sign, giving favourable results",
    neutral: "in a neutral sign, giving mixed results",
    enemy: "in an inimical sign, so results come with effort",
  },
  retrograde: " (retrograde — results turn inward and may come after review or delay)",
  combust: " (combust — close to the Sun, so its independent strength is reduced)",
  sections: {
    personality: "Personality & Lagna", mind: "Mind & Emotions", career: "Career & Profession", wealth: "Wealth & Finances",
    relationships: "Marriage & Relationships", health: "Health & Vitality", education: "Education & Children", spirituality: "Dharma & Spirituality",
    dasha: "Planetary Periods (Dasha)", yogas: "Yogas in Your Chart", doshas: "Doshas", remedies: "Remedies & Lucky Factors",
  },
  t: {
    lagnaIntro: (sign) => `Your ascendant (lagna) is ${sign}.`,
    lordPlaced: (house, sign, lord, lordHouse, lordTopic, dignity) => `Your ${house} falls in ${sign}; its lord ${lord} is placed in the ${lordHouse} (${lordTopic}), ${dignity}.`,
    occupant: (planet, nature, extra) => `${planet} here brings ${nature}${extra}.`,
    emptyHouse: (house) => `No planets occupy the ${house}, so its lord's placement is the main indicator.`,
    moonIntro: (sign) => `Your Moon sign (rashi) is ${sign}.`,
    nakshatra: (nak, pada, lord) => `You were born in ${nak} nakshatra, pada ${pada}, ruled by ${lord}.`,
    currentDasha: (md, ad, mdEnd, adEnd) => `You are running the ${md} Mahadasha (until ${mdEnd}) with the ${ad} Antardasha (until ${adEnd}).`,
    nextDasha: (lord, start) => `The next Mahadasha, of ${lord}, begins on ${start}.`,
    noYogas: "No major classical yogas were detected; results will follow the house lords and dasha periods.",
    weakPlanet: (planet, reason) => `${planet} is ${reason}.`,
    lagnaGem: (lord, gem) => `As your lagna lord is ${lord}, wearing ${gem} (after consulting an astrologer) can strengthen your overall vitality and fortune.`,
    lucky: (color, day, num) => `Lucky colour: ${color}. Favourable day: ${day}. Lucky number: ${num}.`,
    venusNote: (house, dignity) => `Venus, the karaka of love and marriage, sits in your ${house}, ${dignity}.`,
    disclaimer: "Astrological guidance is traditional and indicative. Please use it for reflection, not as a substitute for professional medical, legal or financial advice.",
  },
  dashaThemes: {
    sun: "a period of authority, recognition, government connections and focus on self and father; guard your ego and health of heart and eyes.",
    moon: "a period of emotional growth, public dealings, travel and family matters; nurture your peace of mind.",
    mars: "a period of action, property, courage and competition; channel energy wisely and avoid haste and disputes.",
    mercury: "a period of learning, business, communication and networking; excellent for study and trade.",
    jupiter: "a period of expansion, wisdom, children, wealth and spiritual growth; blessings come through good conduct.",
    venus: "a period of comforts, relationships, arts, vehicles and luxury; balance enjoyment with discipline.",
    saturn: "a period of hard work, responsibility and slow but lasting achievement; patience and service are rewarded.",
    rahu: "a period of ambition, foreign links, technology and sudden changes; stay grounded and avoid shortcuts.",
    ketu: "a period of introspection, detachment and spiritual insight; material matters may feel uncertain.",
  },
  yogas: {
    gajakesari: { name: "Gajakesari Yoga", desc: "Jupiter in a kendra from the Moon gives wisdom, reputation, lasting prosperity and the ability to overcome obstacles." },
    budhaditya: { name: "Budhaditya Yoga", desc: "Sun and Mercury together give sharp intelligence, eloquence and success in education and administration." },
    chandraMangala: { name: "Chandra-Mangala Yoga", desc: "Moon and Mars together give enterprise and earning power, especially through self-effort and business." },
    ruchaka: { name: "Ruchaka Yoga", desc: "A strong Mars in a kendra — one of the Pancha Mahapurusha yogas — gives courage, leadership and physical strength." },
    bhadra: { name: "Bhadra Yoga", desc: "A strong Mercury in a kendra gives intellect, eloquence, business acumen and a youthful nature." },
    hamsa: { name: "Hamsa Yoga", desc: "A strong Jupiter in a kendra gives righteousness, spiritual wisdom, respect and good fortune." },
    malavya: { name: "Malavya Yoga", desc: "A strong Venus in a kendra gives charm, artistic talent, comfort, vehicles and a happy married life." },
    sasa: { name: "Sasa Yoga", desc: "A strong Saturn in a kendra gives authority over people, discipline and success through perseverance." },
    strongLagnaLord: { name: "Strong Lagna Lord", desc: "Your ascendant lord is in its own or exalted sign, a great support for health, confidence and overall success." },
    rajaYoga: { name: "Raja Yoga", desc: "The union of kendra and trikona lords brings rise in status, authority and recognition, especially in their dashas." },
    dhanaYoga: { name: "Dhana Yoga", desc: "The link between the lords of wealth (2nd) and gains (11th) supports steady accumulation of wealth." },
    kemadruma: { name: "Kemadruma Yoga", desc: "The Moon is without planetary support on either side, which can bring periods of loneliness or financial fluctuation. Worship of Lord Shiva and Monday fasts are traditional remedies." },
    vipreetRaja: { name: "Vipreet Raja Yoga", desc: "A lord of a difficult house placed in another difficult house turns adversity into unexpected gains and victory over rivals." },
  },
  doshas: {
    manglik: "Mangal Dosha is present: Mars occupies a sensitive house for marriage. Matching with a compatible chart and Mangal remedies (Hanuman worship on Tuesdays) are advised.",
    manglikCancelled: "Mangal Dosha is present but largely cancelled by Mars's dignity or Jupiter's aspect, so its effect is mild.",
    kaalSarp: "Kaal Sarp Yoga is present: all planets lie on one side of the Rahu–Ketu axis, which can bring struggle before success. Rudrabhishek and Nag Panchami puja are traditional remedies.",
    sadeSati: {
      rising: "Shani Sade Sati has begun (first phase): Saturn transits the 12th from your Moon. Expect increased expenses and changes; stay disciplined.",
      peak: "You are in the peak phase of Shani Sade Sati: Saturn transits your Moon sign. Hard work brings maturity; recite Hanuman Chalisa and serve the needy on Saturdays.",
      setting: "You are in the last phase of Shani Sade Sati: Saturn transits the 2nd from your Moon. Pressures ease gradually; manage finances and speech carefully.",
    },
    none: "No major doshas (Mangal, Kaal Sarp, Sade Sati) are active in your chart.",
  },
  remedies: {
    sun: { gem: "Ruby (Manik)", mantra: "Om Suryaya Namah", day: "Sunday", color: "Saffron / Red", charity: "wheat and jaggery" },
    moon: { gem: "Pearl (Moti)", mantra: "Om Somaya Namah", day: "Monday", color: "White / Silver", charity: "rice, milk and white cloth" },
    mars: { gem: "Red Coral (Moonga)", mantra: "Om Mangalaya Namah", day: "Tuesday", color: "Red", charity: "red lentils (masoor dal)" },
    mercury: { gem: "Emerald (Panna)", mantra: "Om Budhaya Namah", day: "Wednesday", color: "Green", charity: "green moong and green vegetables" },
    jupiter: { gem: "Yellow Sapphire (Pukhraj)", mantra: "Om Gurave Namah", day: "Thursday", color: "Yellow", charity: "chana dal, turmeric and books" },
    venus: { gem: "Diamond / White Sapphire", mantra: "Om Shukraya Namah", day: "Friday", color: "White / Pastel", charity: "sugar, curd and perfume" },
    saturn: { gem: "Blue Sapphire (Neelam) — only after careful trial", mantra: "Om Shanaischaraya Namah", day: "Saturday", color: "Dark blue / Black", charity: "black sesame, mustard oil and help to labourers" },
    rahu: { gem: "Hessonite (Gomed)", mantra: "Om Rahave Namah", day: "Saturday", color: "Smoky grey", charity: "blankets and coconut" },
    ketu: { gem: "Cat's Eye (Lehsunia)", mantra: "Om Ketave Namah", day: "Tuesday", color: "Grey / Brown", charity: "feeding dogs and donating blankets" },
  },
  weakReasons: {
    debilitated: "debilitated — chant its mantra and donate on its day to strengthen it",
    enemy: "in an inimical sign — regular mantra recitation will help",
    combust: "combust by the Sun — worship on its day and avoid wearing its gem without advice",
  },
};
