import type { VastuContent } from "./types.js";

export const en: VastuContent = {
  zoneNames: { N: "North", NNE: "North-North-East", NE: "North-East (Ishanya)", ENE: "East-North-East", E: "East", ESE: "East-South-East", SE: "South-East (Agneya)", SSE: "South-South-East", S: "South", SSW: "South-South-West", SW: "South-West (Nairutya)", WSW: "West-South-West", W: "West", WNW: "West-North-West", NW: "North-West (Vayavya)", NNW: "North-North-West", C: "Centre (Brahmasthan)" },
  zoneAttr: {
    N: "wealth, career opportunities and new beginnings (Kubera)", NNE: "health and immunity", NE: "clarity of mind, wisdom and divine grace",
    ENE: "joy, recreation and refreshment", E: "social connections and recognition (Surya, Indra)", ESE: "churning of thoughts and anxiety",
    SE: "fire, cash flow and vitality (Agni)", SSE: "power, confidence and strength", S: "fame, rest and relaxation (Yama)",
    SSW: "disposal of waste and expenditure", SW: "relationships, stability and skills (Nairutya)", WSW: "education, knowledge and savings",
    W: "gains, profits and fulfilment (Varuna)", WNW: "detox, release of sorrow and letting go", NW: "support, banking and relationships with helpers (Vayu)",
    NNW: "attraction, intimacy and pleasure", C: "the energy core of the home (Brahma), which should stay open and light",
  },
  elements: { water: "Water", air: "Air", fire: "Fire", earth: "Earth", space: "Space" },
  rooms: { entrance: "Main entrance", living: "Living room", dining: "Dining area", kitchen: "Kitchen", masterBedroom: "Master bedroom", bedroom: "Bedroom", toilet: "Toilet / bathroom", pooja: "Pooja room", study: "Study room", staircase: "Staircase", store: "Store room" },
  ratings: { excellent: "Excellent", good: "Good", neutral: "Neutral", avoid: "Not recommended", bad: "Vastu dosha" },
  finding: {
    excellent: (room, zone, attr) => `${room} in the ${zone} zone is ideal. This zone governs ${attr}, and this placement strengthens it.`,
    good: (room, zone, attr) => `${room} in the ${zone} zone is favourable and supports ${attr}.`,
    neutral: (room, zone, attr) => `${room} in the ${zone} zone is acceptable. Keep the space balanced so that ${attr} is not disturbed.`,
    avoid: (room, zone, attr) => `${room} in the ${zone} zone is not recommended and may weaken ${attr}. Simple remedies are suggested below.`,
    bad: (room, zone, attr) => `${room} in the ${zone} zone creates a Vastu dosha affecting ${attr}. Remedies are strongly advised.`,
  },
  ideal: (room, zones) => `Ideal zones for the ${room.toLowerCase()}: ${zones}.`,
  roomRemedies: {
    entrance: "Place a Swastika or Om symbol and a toran of mango leaves at the door; keep the entrance bright, clean and clutter-free. A brass or copper vastu strip under the threshold helps correct the direction.",
    living: "Keep heavy furniture along the South and West walls, and keep the North and East light and open. Add fresh plants and natural light.",
    dining: "Use a square or rectangular table and face East or North while eating. Keep the area well lit.",
    kitchen: "Cook facing East if possible. Place a red or orange element (bulb, tiles) in the kitchen, keep the stove away from the sink, and consider relocating the stove toward the South-East corner of the room.",
    masterBedroom: "Place the bed in the South-West part of the room with your head towards South. Use earthy colours and avoid mirrors facing the bed.",
    bedroom: "Sleep with your head towards South or East. Keep electronics away from the bed and use soft, light colours.",
    toilet: "Keep the toilet door closed and the lid down. Place a bowl of sea salt (change weekly), use light colours, and ensure strong ventilation. A lead or brass vastu strip on the threshold reduces the dosha.",
    pooja: "Face East or North while praying. Keep idols off the floor on a wooden platform, light a diya daily and keep the room clean and uncluttered.",
    study: "Sit facing East or North while studying. Keep the desk tidy and place a Saraswati image or a crystal pyramid on the table.",
    staircase: "Staircases should turn clockwise. Keep the area under the stairs uncluttered and avoid using it as a pooja room or toilet.",
    store: "Keep heavy storage along the South-West walls and avoid storing waste or broken items. Keep the room dry and organised.",
  },
  elementRemedy: {
    water: "This is a Water zone: use blue or white accents and avoid red, fire or heavy earth elements here.",
    air: "This is an Air zone: use green accents and plants, and keep it well ventilated.",
    fire: "This is a Fire zone: use red, orange or pink accents and bright lighting; avoid blue and water features.",
    earth: "This is an Earth zone: use yellow or beige accents and heavy, stable furniture; avoid water features.",
    space: "This is a Space zone: use white, grey or metallic accents and keep it orderly.",
  },
  centerRemedy: "The Brahmasthan (centre) should be kept open, light and free of heavy objects, walls, toilets and kitchens. Place a copper pyramid or keep a light there to activate the centre.",
  missing: (room) => `No ${room.toLowerCase()} was marked on the plan, so it was not analysed.`,
  verdict: {
    excellent: "Your home is in excellent harmony with Vastu principles.",
    good: "Your home is largely Vastu compliant, with a few areas to fine-tune.",
    fair: "Your home has a mix of favourable and unfavourable placements; the remedies below will help balance the energies.",
    poor: "Several important rooms are in unfavourable zones. Following the remedies carefully is recommended, and a detailed on-site consultation may help.",
  },
  generalTips: [
    "Keep the North-East corner clean, light and clutter-free; a water feature or tulsi plant here invites positivity.",
    "Keep the South-West heavier and higher than the North-East — place wardrobes, lockers and heavy furniture there.",
    "Let in morning sunlight from the East; open East and North windows daily.",
    "Remove broken items, stopped clocks and clutter, especially from the centre of the home.",
    "Light a diya or lamp in the pooja area every evening to maintain positive energy.",
  ],
  disclaimer: "Vastu analysis is based on traditional principles and the room positions you marked. For structural changes, consult an expert on site.",
  combined: {
    title: "Personalised Vastu from your Kundali",
    lagnaLordDir: (lord, dir) => `Your lagna lord ${lord} rules the ${dir} direction. Keeping this zone clean, bright and active strengthens your health and confidence.`,
    dashaLordDir: (lord, dir) => `You are running the ${lord} Mahadasha; its direction is ${dir}. Activate this zone to make the most of the current period.`,
    elementDirs: (element, dirs) => `Your Moon sign belongs to the ${element} element; the ${dirs} zones will feel especially nurturing for you.`,
    sleepHead: (dir) => `For restful sleep, keep your head towards the ${dir} while sleeping.`,
    workFacing: (dir) => `Face ${dir} while working or studying to align with your chart.`,
    afflicted: (room, zone, lord) => `Attention: the ${room.toLowerCase()} sits in the ${zone} zone, which belongs to ${lord}, an important planet in your chart. Apply the remedies for this room with priority.`,
    supported: (room, zone, lord) => `The ${room.toLowerCase()} in the ${zone} zone is supported by ${lord}, a key planet in your chart.`,
    colorTip: (zone, color) => `Use ${color} accents in the ${zone} zone to strengthen your lagna lord.`,
    signElements: { fire: "Fire", earth: "Earth", air: "Air", water: "Water" },
  },
};
